version: '3.3'

services:
  db:
    container_name: my-mysql57
    image: mysql:5.7
    #volumes:
    #  - db_data:/var/lib/mysql
    ports:
      - "5306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hmm
      MYSQL_DATABASE: test
      MYSQL_USER: daniel
      MYSQL_PASSWORD: password

volumes:
    db_data: {}
